first_name = input('What is your name?')
print(f'Hello,{first_name}')
radius = float(input('What is the radius of a circle?'))
area = 3.1415926535897932384626433832795028841971693993751058209749445923078164062862089986280348253421170679 * radius
print("Area = ", area)
length_rct = input('What is the length of a rectangle?')
width_rct = input('What is the width of a rectangle?')
length = float(length_rct)
width = float(width_rct)
perimeter = ((length*2)+(width*2))
print(f'Perimeter of a rectangle is : {perimeter}')
area = (length*width)
print(f'Area of a rectangle is: {area}')
number_one = input('What is the first integer?')
number_two = input('What is the second integer?')
number_three = input('What is the third integer?')
one = float(number_one)
two = float(number_two)
three = float(number_three)
sum = (one+two+three)
product = (one*two*three)
average = ((one+two+three)/3)
print("Sum of the given numbers ", sum)
print("Product of the given numbers", product)
print("Average of the given numbers ", average)
users_talents = input('What is your mass in talents?')
users_pounds = input('What is your mass in pounds?')
users_lots = input('What is your mass in lots?')
talents = float(users_talents)
pounds = float(users_pounds)
lots = float(users_lots)
lots = 13.3
pounds = 32*lots
talents = 20*pounds
output = (lots+pounds+talents)
print("The weight in grams is ", output)
grams = float(output)
kilograms = grams / 1000
print("The weight in kilograms is", kilograms)

